/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cute_cat.glb -T 
Files: cute_cat.glb [529.88KB] > C:\Users\DOT\Desktop\donnaport\public\models\cute_cat-transformed.glb [502.82KB] (5%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cute_cat-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.defaultMat} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cute_cat-transformed.glb')
